### ISSUE TITLE
Team coordination

### ISSUE THREAD

**Issue by AlteOgre** [VulcanForge/pvp-mode#8]
As CM doesn't use Facebook: What about moving to Discord? Do we all use that? Alternative is to start Issue discussion threads here. I'd rather not have multiple platforms where we coordinate the what, when and how of any features and our efforts to realise them.

**Comment by CraftedMods** [comment]
I think the issues would be the best option, because they allow us to reference commits, milestones, PRs and so on and are integrated into Github.

**Comment by VulcanForge** [comment]
Agreed. New features can be suggested on the wiki or on Discord, but bugfixes and under-the-hood code changes should all go here.

**Comment by AlteOgre** [comment]
We're not on Discord yet, and if we can avoid it, we shouldn't. I'm thinking launch a new thread on the wiki with the release of v1.0 first public beta, and then close our Facebook group. I will then transfer any relevant notes we made in that group to new issue thread(s) here, so we have a general discussion thread and maybe one or a few other decicated ones. Would that be sufficient? Any possible reason to launch a Discord for us and/or for interaction with the client base? Or would this environment and a wiki thread do?

Note that Mevans still hasn't formally endorsed the mod yet, so we cannot create a wiki page on it.

Also note that CM did get endorsement for his NEI addon, so he could create a wiki page for it if he'd wish. ;)

**Comment by Mahtaran** [comment]
Might want to move the notes to a Github Wiki page instead. And I'd go for a Discord group as that's more intuitive to me (and my school doesn't block Discord while it does block the wikia), but if you want to go full github/wikia I'll adapt.

**Comment by VulcanForge** [comment]
Here are the things I want to do when 1.0 has been pushed onto the master branch. I intend to make Mahtaran and CraftedMods collaborators. I would like to change the structure of this repository to go one directory up in the path (with gitignore for all the Minecraft server test files and such). I would also like to squash all previous commits into one and agree on a protocol for changing repository code so that we can all agree on what happens. I will even consider changing the formatting settings to something mutually agreeable. Are the two coders here happy to be collaborators?

**Comment by Mahtaran** [comment]
More than happy!

**Comment by AlteOgre** [comment]
@Maht About moving notes to GitHub wiki: Well, yeah. That is what I've already been doing with the planned features list on the wiki page. Not all is clearly fleshed out to mention it there though. Good hint anyway, so I'll ponder a way to distinguish and use the GitHub wiki a bit broader. I'll create a couple of additional pages for specific parts now all cluttered on the (single) main page.
Let me take care of that crap, you guys do coding magic. ;)

**Comment by Mahtaran** [comment]
👍🏻

**Comment by CraftedMods** [comment]
Sure. I suggest that we're still using pull requests, because they're a great opportunity for the other coders to review the changes one made. This way it's less likely that someone introduces bugs. So I suggest that we keep the two branches master and development - but normally we don't commit directly to this branch, but open a PR. Then at least one person should review this, if we all agree on the changes, we can merge into dev. Changing the repository structure is also good, because currently I have to copy and paste the contents of build.gradle and EGit doesn't work well with this structure.

**Comment by Mahtaran** [comment]
Yeah, I'm for that too. I just thought that "I will then transfer any relevant notes we made in that group to new issue thread(s) here" could be much better done on a wiki page

**Comment by CraftedMods** [comment]
Github also supports projects - they can help us with coordinaton too.

**Comment by Mahtaran** [comment]
Oh yeah, that's true too! So many options...

**Comment by VulcanForge** [comment]
Both CraftedMods and Mahtaran are now collaborators. I got 52 emails this morning from GitHub and I cannot keep up with all the pull requests and issues since I am very busy with math research. I'm going to take a back seat on the mod for a while. Thanks for all the contributions!

**Comment by Mahtaran** [comment]
Okay, take your time!

**Comment by CraftedMods** [comment]
I think we can close this. and continue discussion on #21 and #22.
